# aws cloudformation create-stack \
# --template-body file://ecs-windows-cluster-service.yaml \
# --stack-name test-ecs-service-stack \
# --parameters \
# ParameterKey=ClusterId,ParameterValue=arn:aws:ecs:xxxx \
# ParameterKey=ContainerName,ParameterValue=test-container \
# ParameterKey=ContainerImage,ParameterValue=xxx

AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    ClusterId:
        Description: ECS Cluster Id for running this task and service
        Type: String

    ContainerName:
        Description: Container Name
        Type: String

    ContainerImage:
        Description: Container Image URL
        Type: String

Resources:
  Task: 
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities:
        - "EC2"
      ContainerDefinitions: 
        - 
          Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Cpu: "20"
          Memory: 512
          Essential: true

  Service: 
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref ClusterId
      DesiredCount: 2
      TaskDefinition: !Ref Task
